Use MONO_SHARED_DIR to point to a temporary wapi directory - mono needs
	* tools/beagle-crawl-system.in: Use MONO_SHARED_DIR to point to a
	temporary wapi directory - mono needs one for beagle-build-index.

diff --git a/tools/beagle-crawl-system.in b/tools/beagle-crawl-system.in
--- a/tools/beagle-crawl-system.in
+++ b/tools/beagle-crawl-system.in
@@ -30,6 +30,12 @@ umask 022
 
 CRAWL_USER=beagleindex
 
+export TMPDIR=/tmp
+
+# Mono requires a writable wapi directory
+MONO_SHARED_DIR=`mktemp -d -p $TMPDIR .beagleindexwapi.XXXXXXXXXX`|| ( echo "Can't create wapi directory!" ; exit 1 )
+chown $CRAWL_USER $MONO_SHARED_DIR
+
 for crawl_file in @sysconfdir@/beagle/crawl-*; do 
     unset CRAWL_ENABLED CRAWL_DISABLE_FILTERING CRAWL_RECURSIVE CRAWL_CACHE_TEXT CRAWL_ALLOW_PATTERNS CRAWL_DENY_PATTERNS CRAWL_PATHS CRAWL_INDEX_NAME
 
@@ -58,10 +64,12 @@ for crawl_file in @sysconfdir@/beagle/crawl-*; do
                 IONICE="$IONICE -c 3"
             fi
 
-            export TMPDIR=/tmp
-	    eval nice -n 19 $IONICE su $CRAWL_USER -c \"@sbindir@/beagle-build-index --target @localstatedir@/cache/beagle/indexes/$CRAWL_INDEX_NAME $OPTIONS $CRAWL_PATHS\" > /dev/null 2>&1
+	    eval nice -n 19 $IONICE su $CRAWL_USER -s /bin/bash -c \" MONO_SHARED_DIR=$MONO_SHARED_DIR @sbindir@/beagle-build-index --target @localstatedir@/cache/beagle/indexes/$CRAWL_INDEX_NAME $OPTIONS $CRAWL_PATHS\" > /dev/null 2>&1
 	fi
     fi
 done
+
+# delete wapi directory
+rm -rf $MONO_SHARED_DIR
 
 exit 0
